# Generated by Selenium IDE
import pytest
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains

class TestCadastroInstituio():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_cadastroInstituio(self):
        self.driver.get("http://127.0.0.1:8000/login/login/")
        self.driver.set_window_size(974, 1032)

        time.sleep(0.5)
        self.driver.find_element(By.LINK_TEXT, "Cadastre-se").click()

        time.sleep(0.5)
        self.driver.find_element(By.ID, "id_instituicao_cnpj").click()
        self.driver.find_element(By.ID, "id_instituicao_cnpj").send_keys("10.744.098/0001-45")

        time.sleep(0.5)
        self.driver.find_element(By.ID, "id_instituicao_nome").click()

        time.sleep(0.5)
        self.driver.find_element(By.ID, "id_instituicao_telefone").click()
        self.driver.find_element(By.ID, "id_instituicao_telefone").send_keys("(86) 98173-2738")

        time.sleep(0.5)
        self.driver.find_element(By.ID, "id_cep").click()

        time.sleep(0.5)
        self.driver.find_element(By.ID, "id_rua").click()

        time.sleep(0.5)
        self.driver.find_element(By.ID, "id_complemento").click()
        self.driver.find_element(By.ID, "id_complemento").send_keys("Instituição")

        time.sleep(0.5)
        self.driver.find_element(By.ID, "id_primeiro_nome").click()
        self.driver.find_element(By.ID, "id_primeiro_nome").send_keys("Kawan")

        time.sleep(0.5)
        self.driver.find_element(By.ID, "id_sobrenome").send_keys("Loureiro")

        time.sleep(0.5)
        self.driver.find_element(By.ID, "id_cpf").click()
        self.driver.find_element(By.ID, "id_cpf").send_keys("639.235.563-49")

        time.sleep(0.5)
        self.driver.find_element(By.ID, "id_email").click()
        self.driver.find_element(By.ID, "id_email").send_keys("kawanloureiro@gmail.com")

        time.sleep(0.5)
        self.driver.find_element(By.ID, "id_cpf").click()

        time.sleep(0.5)
        self.driver.find_element(By.CSS_SELECTOR, ".btn-user-signup").click()


class TestAlertaErroCNPJCPF():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}
    
    def teardown_method(self, method):
        self.driver.quit()
    
    def test_alertaErroCNPJCPF(self):
        self.driver.get("http://127.0.0.1:8000/login/login/")
        time.sleep(0.5)
        self.driver.set_window_size(974, 1032)
        time.sleep(0.5)
        self.driver.find_element(By.LINK_TEXT, "Cadastre-se").click()
        time.sleep(0.5)
        self.driver.find_element(By.ID, "id_instituicao_cnpj").click()
        time.sleep(0.5)
        self.driver.find_element(By.ID, "id_instituicao_cnpj").send_keys("10.392.0300/0290-939")
        time.sleep(0.5)
        element = self.driver.find_element(By.CSS_SELECTOR, ".form-endereco > .form-label")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).click_and_hold().perform()
        time.sleep(0.5)
        element = self.driver.find_element(By.ID, "id_instituicao_nome")
        actions.move_to_element(element).release().perform()
        time.sleep(0.5)
        self.driver.find_element(By.CSS_SELECTOR, "form").click()
        time.sleep(0.5)
        self.driver.find_element(By.CSS_SELECTOR, "html").click()
        time.sleep(0.5)
        self.driver.find_element(By.ID, "id_instituicao_cnpj").click()
        time.sleep(0.5)
        self.driver.find_element(By.ID, "id_instituicao_cnpj").send_keys("10.744.098/0001-45")
        time.sleep(0.5)
        self.driver.find_element(By.CSS_SELECTOR, "p:nth-child(3)").click()
        time.sleep(0.5)
        self.driver.find_element(By.ID, "id_instituicao_telefone").click()
        time.sleep(0.5)
        self.driver.find_element(By.ID, "id_instituicao_telefone").send_keys("(86) 98173-2738")
        time.sleep(0.5)
        self.driver.close()


class TestLogineCadastrodeCurso():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_logineCadastrodeCurso(self):
    self.driver.get("http://127.0.0.1:8000/login/login/")
    time.sleep(0.5)
    self.driver.set_window_size(1553, 1032)
    time.sleep(0.5)
    self.driver.find_element(By.ID, "id_login").click()
    time.sleep(0.5)
    self.driver.find_element(By.ID, "id_login").send_keys("kawanloure@gmail.com")
    time.sleep(0.5)
    self.driver.find_element(By.ID, "id_password").click()
    time.sleep(0.5)
    self.driver.find_element(By.ID, "id_password").send_keys("07821588032")
    time.sleep(0.5)
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
    time.sleep(0.5)
    self.driver.find_element(By.CSS_SELECTOR, ".btn-sidebar:nth-child(2) .text").click()
    time.sleep(0.5)
    self.driver.find_element(By.LINK_TEXT, "Cadastrar Novo Curso").click()
    time.sleep(0.5)
    self.driver.find_element(By.ID, "id_nome_curso").click()
    time.sleep(0.5)
    self.driver.find_element(By.ID, "id_nome_curso").send_keys("Análise e Desenvolvimento de Sistemas")
    time.sleep(0.5)
    self.driver.find_element(By.ID, "id_area").click()
    time.sleep(0.5)
    self.driver.find_element(By.ID, "id_coordenador").click()
    time.sleep(0.5)
    self.driver.find_element(By.ID, "id_coordenador").send_keys("Marcel Moura")
    time.sleep(0.5)
    self.driver.find_element(By.CSS_SELECTOR, ".form-inicial:nth-child(4)").click()
    time.sleep(0.5)
    self.driver.find_element(By.ID, "id_email_coordenador").click()
    time.sleep(0.5)
    self.driver.find_element(By.ID, "id_email_coordenador").send_keys("ads.coordenaifpi@ifpi.edu.br")
    time.sleep(0.5)
    self.driver.find_element(By.ID, "id_descricao").click()
    time.sleep(0.5)
    self.driver.find_element(By.ID, "id_descricao").send_keys("Curso de Analise e Desenvolvimento de Sistemas")
    time.sleep(0.5)
    self.driver.find_element(By.CSS_SELECTOR, ".btn-user-signup").click()
    time.sleep(0.5)
    self.driver.find_element(By.CSS_SELECTOR, ".btn-close").click()
    time.sleep(0.5)
    self.driver.close()

class TestCadastrodeEmpresa():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}
    
    def teardown_method(self, method):
        self.driver.quit()
    
    def test_cadastrodeEmpresa(self):
        self.driver.get("http://127.0.0.1:8000/login/login/")
        time.sleep(0.5)
        self.driver.set_window_size(1553, 1032)
        time.sleep(0.5)
        self.driver.find_element(By.ID, "id_login").click()
        time.sleep(0.5)
        self.driver.find_element(By.ID, "id_login").send_keys("kawanloure@gmail.com")
        time.sleep(0.5)
        self.driver.find_element(By.ID, "id_password").click()
        time.sleep(0.5)
        self.driver.find_element(By.ID, "id_password").send_keys("07821588032")
        time.sleep(0.5)
        self.driver.find_element(By.CSS_SELECTOR, "button").click()
        time.sleep(0.5)
        self.driver.find_element(By.CSS_SELECTOR, ".btn-sidebar:nth-child(4) .text").click()
        time.sleep(0.5)
        self.driver.find_element(By.LINK_TEXT, "Cadastrar Nova Empresa").click()
        time.sleep(0.5)
        self.driver.find_element(By.ID, "id_empresa_cnpj").click()
        time.sleep(0.5)
        self.driver.find_element(By.ID, "id_empresa_cnpj").send_keys("38199480000134")
        time.sleep(0.5)
        self.driver.find_element(By.ID, "id_empresa_nome").click()
        time.sleep(0.5)
        self.driver.find_element(By.CSS_SELECTOR, ".form-endereco").click()
        time.sleep(0.5)
        self.driver.find_element(By.ID, "id_cep").click()
        time.sleep(0.5)
        self.driver.find_element(By.ID, "id_numero").click()
        time.sleep(0.5)
        self.driver.find_element(By.CSS_SELECTOR, ".form-linha1:nth-child(1) > .form-inicial:nth-child(1)").click()
        time.sleep(0.5)
        self.driver.find_element(By.ID, "id_primeiro_nome").click()
        time.sleep(0.5)
        self.driver.find_element(By.ID, "id_primeiro_nome").send_keys("Sergio")
        time.sleep(0.5)
        self.driver.find_element(By.ID, "id_sobrenome").send_keys("Costa")
        time.sleep(0.5)
        self.driver.find_element(By.ID, "id_cpf").click()
        time.sleep(0.5)
        self.driver.find_element(By.ID, "id_cpf").send_keys("80916369030")
        time.sleep(0.5)
        self.driver.find_element(By.ID, "id_cargo").click()
        time.sleep(0.5)
        self.driver.find_element(By.ID, "id_cargo").send_keys("Gerente")
        time.sleep(0.5)
        self.driver.find_element(By.ID, "id_telefone").send_keys("(83) 89389-3893")
        time.sleep(0.5)
        self.driver.find_element(By.ID, "id_email").click()
        time.sleep(0.5)
        self.driver.find_element(By.ID, "id_email").send_keys("sergiocosta@gmail.com")
        time.sleep(0.5)
        self.driver.find_element(By.CSS_SELECTOR, ".btn-user-signup").click()
        time.sleep(0.5)
        self.driver.find_element(By.CSS_SELECTOR, ".btn-close").click()
  
class TestCadastrodeEstagirio():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_cadastrodeEstagirio(self):
    self.driver.get("http://127.0.0.1:8000/login/login/")
    self.driver.set_window_size(1751, 1032)
    time.sleep(0.5)
    self.driver.find_element(By.ID, "id_login").click()
    time.sleep(0.5)
    self.driver.find_element(By.ID, "id_login").send_keys("kawanloure@gmail.com")
    time.sleep(0.5)
    self.driver.find_element(By.ID, "id_password").click()
    time.sleep(0.5)
    element = self.driver.find_element(By.ID, "id_password")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    time.sleep(0.5)
    self.driver.find_element(By.ID, "id_password").send_keys("07821588032")
    time.sleep(0.5)
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
    time.sleep(0.5)
    self.driver.find_element(By.CSS_SELECTOR, ".btn-sidebar:nth-child(3) .text").click()
    time.sleep(0.5)
    self.driver.find_element(By.LINK_TEXT, "Cadastrar Novo Estagiário").click()
    time.sleep(0.5)
    self.driver.find_element(By.ID, "id_primeiro_nome").send_keys("Paulo")
    time.sleep(0.5)
    self.driver.find_element(By.ID, "id_sobrenome").send_keys("Roberto")
    time.sleep(0.5)
    self.driver.find_element(By.ID, "id_cpf").send_keys("26590029083")
    time.sleep(0.5)
    self.driver.find_element(By.ID, "id_email").send_keys("pauloroberto@gmail.com")
    time.sleep(0.5)
    self.driver.find_element(By.ID, "id_matricula").send_keys("2023113tads0003")
    time.sleep(0.5)
    self.driver.find_element(By.ID, "id_telefone").send_keys("(83) 89389-3893")
    time.sleep(0.5)
    self.driver.find_element(By.CSS_SELECTOR, ".btn-user-signup").click()
    time.sleep(0.5)
    self.driver.find_element(By.CSS_SELECTOR, ".btn-close").click()
    self.driver.close()