# Generated by Django 5.1.2 on 2025-06-16 22:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoordenadorExtensao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Use apenas números.', regex='^[0-9]+$')])),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.RegexValidator(message='Use um e-mail valido.', regex='^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$')])),
                ('nome_completo', models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(message='Use apenas letras.', regex='^[a-zA-Z ]+$')])),
            ],
        ),
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_curso', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Use apenas letras.', regex='^[a-zA-ZáéíóúÁÉÍÓÚãõÃÕçÇ\\s]+$')])),
                ('descricao', models.CharField(max_length=250)),
                ('area', models.CharField(choices=[('Saúde', 'Saude'), ('Tecnologia', 'Tecnologia'), ('Gestão e Negócios', 'Gestao E Negocios'), ('Engenharia e Construção', 'Engenharia E Construcao'), ('Eletrônica e Automação', 'Eletronica E Automacao'), ('Educação', 'Educacao'), ('Outros', 'Outros')], default='Tecnologia', max_length=50)),
                ('coordenador', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Use apenas letras.', regex='^[a-zA-ZáéíóúÁÉÍÓÚãõÃÕçÇ\\s]+$')])),
                ('email_coordenador', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.RegexValidator(message='Use um e-mail valido.', regex='^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('convenio', models.CharField(blank=True, max_length=80, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Use apenas números.', regex='^[0-9]{4}/[0-9]{4}$')])),
                ('empresa_nome', models.CharField(max_length=250, validators=[django.core.validators.RegexValidator(message='Use apenas letras.', regex='^[a-zA-Z ]+$')])),
                ('cnpj', models.CharField(max_length=250, unique=True, validators=[django.core.validators.RegexValidator(message='Use apenas números.', regex='^[0-9]{2}\\.[0-9]{3}\\.[0-9]{3}/[0-9]{4}-[0-9]{2}$')])),
                ('razao_social', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.RegexValidator(message='Use um e-mail valido.', regex='^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$')])),
                ('atividades', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=10)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=50)),
                ('cep', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Use apenas números.', regex='^[0-9]+$')])),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estagio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bolsa_estagio', models.FloatField(blank=True, default=0, null=True)),
                ('area', models.CharField(max_length=250)),
                ('tipo_estagio', models.TextField(choices=[('Não obrigatório', 'Nao Obrigatorio'), ('Obrigatório', 'Obrigatorio')], default='Não obrigatório')),
                ('status', models.TextField(choices=[('Em andamento', 'Em Andamento'), ('Concluído', 'Concluido')], default='Em andamento')),
                ('descricao', models.TextField(max_length=1000)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('turno', models.TextField(choices=[('Manhã', 'Manha'), ('Tarde', 'Tarde'), ('Noite', 'Noite')], default='Manhã')),
                ('auxilio_transporte', models.FloatField(blank=True, default=0, null=True)),
                ('orientador', models.TextField(blank=True, max_length=100, null=True)),
                ('pdf_termo', models.FileField(blank=True, null=True, upload_to='termos/')),
            ],
        ),
        migrations.CreateModel(
            name='RelatorioEstagio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('termo', 'Termo de Compromisso'), ('relatorio_semestral', 'Relatório Semestral de Atividades'), ('avaliacao', 'Relatório de Avaliação'), ('conclusao', 'Termo de Conclusão/Rescisão')], max_length=30)),
                ('data_prevista', models.DateField()),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='relatorios/')),
                ('preenchido', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='Use apenas números.', regex='^[0-9]+$')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(max_length=20)),
                ('nome_completo', models.CharField(max_length=150)),
                ('cargo', models.CharField(max_length=254)),
            ],
        ),
    ]
