# Generated by Django 5.1.2 on 2025-01-10 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estagio',
            name='auxilio_transporte',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='estagio',
            name='bolsa_estagio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estagio',
            name='data_fim',
            field=models.DateField(max_length=10),
        ),
        migrations.AlterField(
            model_name='estagio',
            name='data_inicio',
            field=models.DateField(max_length=10),
        ),
        migrations.AlterField(
            model_name='estagio',
            name='status',
            field=models.CharField(choices=[('Em andamento', 'Em Andamento'), ('Concluido', 'Concluido')], default='Em andamento', max_length=50),
        ),
    ]
