# Generated by Django 5.1.4 on 2025-01-13 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estagiario',
            name='telefone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='estagio',
            name='area',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='estagio',
            name='bolsa_estagio',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='estagio',
            name='data_fim',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='estagio',
            name='data_inicio',
            field=models.DateField(),
        ),
    ]
