# Generated by Django 5.1.2 on 2025-01-12 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_estagiario_instituicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estagio',
            name='status',
            field=models.TextField(choices=[('Em andamento', 'Em Andamento'), ('Concluido', 'Concluido')], default='Em andamento'),
        ),
    ]
