# Generated by Django 5.1.2 on 2024-12-12 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_estagiario_instituicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='estagio',
            name='auxilio_transporte',
            field=models.FloatField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estagio',
            name='turno',
            field=models.TextField(choices=[('Manha', 'Manha'), ('Tarde', 'Tarde'), ('Noite', 'Noite')]),
        ),
    ]
