# Generated by Django 5.1.2 on 2024-12-13 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_estagio_auxilio_transporte_alter_estagio_turno'),
    ]

    operations = [
        migrations.AddField(
            model_name='estagio',
            name='auxilio_transporte',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estagio',
            name='bolsa_estagio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estagio',
            name='turno',
            field=models.TextField(choices=[('Manha', 'Manha'), ('Tarde', 'Tarde'), ('Noite', 'Noite')]),
        ),
    ]
