# Generated by Django 5.1.4 on 2025-01-06 19:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_estagio_auxilio_transporte_alter_estagio_turno'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportTermoEstagio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='termo_estagio/%Y/%m/%d/')),
            ],
        ),
        migrations.AlterField(
            model_name='coordenadorextensao',
            name='cpf',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Use apenas números.', regex='^[0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='coordenadorextensao',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.RegexValidator(message='Email invalido.', regex='^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\\.[a-zA-Z0-9-.]+$')]),
        ),
        migrations.AlterField(
            model_name='coordenadorextensao',
            name='instituicao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.instituicao', validators=[django.core.validators.RegexValidator(message='Use apenas letras e espaços.', regex='^[A-Za-z\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='coordenadorextensao',
            name='primeiro_nome',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Use apenas letras e espaços.', regex='^[A-Za-z\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='coordenadorextensao',
            name='sobrenome',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Use apenas letras e espaços.', regex='^[A-Za-z\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cnpj',
            field=models.CharField(max_length=250, validators=[django.core.validators.RegexValidator(message='Use apenas números.', regex='^[0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.RegexValidator(message='Email invalido.', regex='^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\\.[a-zA-Z0-9-.]+$')]),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='endereco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.endereco', validators=[django.core.validators.RegexValidator(message='Use apenas letras e espaços.', regex='^[A-Za-z\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nome',
            field=models.CharField(max_length=250, validators=[django.core.validators.RegexValidator(message='Use apenas letras e espaços.', regex='^[A-Za-z\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='razao_social',
            field=models.CharField(max_length=250, validators=[django.core.validators.RegexValidator(message='Use apenas letras e espaços.', regex='^[A-Za-z\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='cep',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Use apenas números.', regex='^[0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='numero',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Use apenas números.', regex='^[0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='rua',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Use apenas letras e espaços.', regex='^[A-Za-z\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='estagiario',
            name='cpf',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Use apenas números.', regex='^[0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='estagiario',
            name='curso',
            field=models.CharField(max_length=55, validators=[django.core.validators.RegexValidator(message='Use apenas letras e espaços.', regex='^[A-Za-z\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='estagiario',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.RegexValidator(message='Email invalido.', regex='^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\\.[a-zA-Z0-9-.]+$')]),
        ),
        migrations.AlterField(
            model_name='estagiario',
            name='endereco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.endereco', validators=[django.core.validators.RegexValidator(message='Use apenas letras e espaços.', regex='^[A-Za-z\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='estagiario',
            name='instituicao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.instituicao', validators=[django.core.validators.RegexValidator(message='Use apenas letras e espaços.', regex='^[A-Za-z\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='estagiario',
            name='matricula',
            field=models.CharField(max_length=55, validators=[django.core.validators.RegexValidator(message='Use apenas números.', regex='^[0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='estagiario',
            name='primeiro_nome',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Use apenas letras e espaços.', regex='^[A-Za-z\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='estagiario',
            name='sobrenome',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Use apenas letras e espaços.', regex='^[A-Za-z\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='estagiario',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='estagiario',
            name='telefone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Use apenas números.', regex='^[0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='estagio',
            name='area',
            field=models.CharField(max_length=250, validators=[django.core.validators.RegexValidator(message='Use apenas letras e espaços.', regex='^[A-Za-z\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='estagio',
            name='auxilio_transporte',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.RegexValidator(message='Use apenas números.', regex='^[0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='estagio',
            name='bolsa_estagio',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='Use apenas números.', regex='^[0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='estagio',
            name='data_fim',
            field=models.DateField(max_length=10, validators=[django.core.validators.RegexValidator(message='Use apenas números.', regex='^[0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='estagio',
            name='data_inicio',
            field=models.DateField(max_length=10, validators=[django.core.validators.RegexValidator(message='Use apenas números.', regex='^[0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='estagio',
            name='descricao',
            field=models.TextField(max_length=1000, validators=[django.core.validators.RegexValidator(message='Use apenas letras e espaços.', regex='^[A-Za-z\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='estagio',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.empresa', validators=[django.core.validators.RegexValidator(message='Use apenas letras e espaços.', regex='^[A-Za-z\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='estagio',
            name='estagiario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.estagiario', validators=[django.core.validators.RegexValidator(message='Use apenas letras e espaços.', regex='^[A-Za-z\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='estagio',
            name='instituicao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.instituicao', validators=[django.core.validators.RegexValidator(message='Use apenas letras e espaços.', regex='^[A-Za-z\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='estagio',
            name='status',
            field=models.TextField(choices=[('Em andamento', 'Em Andamento'), ('Concluido', 'Concluido')], default='Em andamento'),
        ),
        migrations.AlterField(
            model_name='estagio',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.supervisor', validators=[django.core.validators.RegexValidator(message='Use apenas letras e espaços.', regex='^[A-Za-z\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='estagio',
            name='turno',
            field=models.TextField(choices=[('Manha', 'Manha'), ('Tarde', 'Tarde'), ('Noite', 'Noite')], default='Manha'),
        ),
        migrations.AlterField(
            model_name='instituicao',
            name='cnpj',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Use apenas números.', regex='^[0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='instituicao',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.RegexValidator(message='Email invalido.', regex='^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\\.[a-zA-Z0-9-.]+$')]),
        ),
        migrations.AlterField(
            model_name='instituicao',
            name='endereco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.endereco', validators=[django.core.validators.RegexValidator(message='Use apenas letras e espaços.', regex='^[A-Za-z\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='instituicao',
            name='nome',
            field=models.CharField(max_length=250, validators=[django.core.validators.RegexValidator(message='Use apenas letras e espaços.', regex='^[A-Za-z\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='instituicao',
            name='telefone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Use apenas números.', regex='^[0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='cargo',
            field=models.CharField(max_length=254, validators=[django.core.validators.RegexValidator(message='Use apenas letras e espaços.', regex='^[A-Za-z\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='cpf',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Use apenas números.', regex='^[0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.RegexValidator(message='Email invalido.', regex='^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\\.[a-zA-Z0-9-.]+$')]),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.empresa', validators=[django.core.validators.RegexValidator(message='Use apenas letras e espaços.', regex='^[A-Za-z\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='primeiro_nome',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Use apenas letras e espaços.', regex='^[A-Za-z\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='sobrenome',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Use apenas letras e espaços.', regex='^[A-Za-z\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='telefone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Use apenas números.', regex='^[0-9]+$')]),
        ),
    ]
