# Generated by Django 5.1.2 on 2024-12-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_estagio_auxilio_transporte_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estagio',
            name='auxilio_transporte',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='estagio',
            name='bolsa_estagio',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='estagio',
            name='status',
            field=models.TextField(choices=[('Ativo', 'Ativo'), ('Pendente', 'Pendente'), ('Concluído', 'Concluido')]),
        ),
    ]
