# Generated by Django 5.1.2 on 2025-01-06 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_estagio_auxilio_transporte_alter_estagio_turno'),
        ('dashboard', '0004_alter_estagio_auxilio_transporte_and_more'),
    ]

    operations = [
    ]
