# Generated by Django 5.1.2 on 2025-01-12 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_importtermoestagio_alter_coordenadorextensao_cpf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='atividades',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
