# Generated by Django 5.1.4 on 2025-01-10 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_importtermoestagio_alter_coordenadorextensao_cpf_and_more'),
        ('dashboard', '0005_merge_20250106_1558'),
    ]

    operations = [
    ]
